openapi: 3.0.3
info:
  title: Hello World Greet Helidon MP Application
  version: "1.0"
servers:
- url: /
paths:
  /greet:
    get:
      operationId: getDefaultMessage
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GreetResponse'
          description: OK
      summary: Gets default greet message
      tags:
      - greet
      x-accepts: application/json
  /greet/{name}:
    get:
      operationId: getMessage
      parameters:
      - explode: false
        in: path
        name: name
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GreetResponse'
          description: OK
      summary: Gets message based on the parameter name
      tags:
      - greet
      x-accepts: application/json
  /greet/greeting:
    put:
      operationId: updateGreeting
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GreetUpdate'
        required: true
      responses:
        "204":
          description: Greeting updated
        "400":
          description: JSON body content did not contain setting for 'greeting'
      summary: Set the greeting to use in future messages.
      tags:
      - greet
      x-content-type: application/json
      x-accepts: application/json
components:
  schemas:
    GreetResponse:
      example:
        date: 2000-01-23
        message: message
      properties:
        message:
          type: string
        date:
          format: date
          type: string
      type: object
    GreetUpdate:
      example:
        greeting: greeting
      properties:
        greeting:
          type: string
      type: object
